### ISSUE TITLE
[WinForms] Start returns `Invalid thread identifier.` exception.

### ISSUE THREAD

**Issue by DoubleDebug** [HavenDV/H.Hooks#2]
After installing the H.Hooks nuget package in VS, I tried using the sample code from the README. I got the following error:

> 'LowLevelKeyboardHook' does not contain a definition for 'KeyUp' and no accessible extension method 'KeyUp' accepting a first argument of type 'LowLevelKeyboardHook' could be found (are you missing a using directive or an assembly reference?)

The intellisense showed that the hook had EventHandlers called Up and Down, not KeyUp and KeyDown, so I assumed they were just renamed in a later version. After changing my code, I was happy because I didn't get any compile errors, however, after running the app, I got a runtime error:

> Invalid thread identifier.

Here's the code that I used (sample code from README), the error message and stack trace:
![Error message](https://user-images.githubusercontent.com/62041862/124970413-27719180-e028-11eb-8550-4ba5f73c8d1b.png)

Stack trace:

> at H.Hooks.Core.Interop.InteropUtilities.ThrowWin32Exception()\r\n   at H.Hooks.Core.Interop.InteropUtilities.Check(Boolean value)\r\n   at H.Hooks.Hook.Stop()\r\n   at H.Hooks.Hook.Dispose()\r\n   at Keylogger.Keylogger.Keylogger_Load(Object sender, EventArgs e) in D:\\Projects\\C#\\Keylogger\\Keylogger\\Keylogger.cs:line 28\r\n   at System.Windows.Forms.Form.OnLoad(EventArgs e)\r\n   at MetroSet_UI.Forms.MetroSetForm.OnLoad(EventArgs e)\r\n   at System.Windows.Forms.Form.OnCreateControl()\r\n   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)\r\n   at System.Windows.Forms.Control.CreateControl()\r\n   at System.Windows.Forms.Control.WmShowWindow(Message& m)\r\n   at System.Windows.Forms.Control.WndProc(Message& m)\r\n   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)\r\n   at System.Windows.Forms.ContainerControl.WndProc(Message& m)\r\n   at System.Windows.Forms.Form.WmShowWindow(Message& m)\r\n   at System.Windows.Forms.Form.WndProc(Message& m)\r\n   at MetroSet_UI.Forms.MetroSetForm.WndProc(Message& message)\r\n   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)\r\n   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)\r\n   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)"	string

**Comment by HavenDV** [comment]
Which TargetFramework are you use?

**Comment by DoubleDebug** [comment]
> Which TargetFramework are you use?

.NET 5.0

**Comment by HavenDV** [comment]
The example has been fixed.

Have you tried using a console application?
I have tested the library only inside a console application(net4.8 and net5.0) and in WPF(net4.8 and net5.0).
![image](https://user-images.githubusercontent.com/3002068/125075416-e948a080-e101-11eb-8453-2b3d1d6e29e0.png)

**Comment by DoubleDebug** [comment]
Yes, it works fine with a console application.
I also tried using .NET 4.7.2 and it works there too. The only issue seems to be with .NET 5.0.

.NET Core obviously doesn't work because it's cross-platform and we're working with Windows hooks here. Thanks for the reply!

**Comment by JyuuAra** [comment]
Hi, I also meet this exception.
Installed version 1.4.9 from Nuget. (.NET 45)
Path : H.Hooks.1.4.9/lib/net45/H.Hooks.dll
Assembly Info : Targets .NET 4.x.
Thanks

**Comment by HavenDV** [comment]
> Hi, I also meet this exception.
> Installed version 1.4.9 from Nuget. (.NET 45)
> Path : H.Hooks.1.4.9/lib/net45/H.Hooks.dll
> Assembly Info : Targets .NET 4.x.
> Thanks

Also WinForms app?

**Comment by JyuuAra** [comment]
> > Hi, I also meet this exception.
> > Installed version 1.4.9 from Nuget. (.NET 45)
> > Path : H.Hooks.1.4.9/lib/net45/H.Hooks.dll
> > Assembly Info : Targets .NET 4.x.
> > Thanks
> 
> Also WinForms app?

Not WinForms.

**Comment by HavenDV** [comment]
I still don't have time because of my main job, but I think this will help me (or someone else who decides to figure it out) in the future:
https://devblogs.microsoft.com/oldnewthing/20040223-00/?p=40503
https://docs.microsoft.com/en-us/windows/win32/procthread/thread-handles-and-identifiers

**Comment by HavenDV** [comment]
Fixed using https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-postthreadmessagea#remarks
