### ISSUE TITLE
How to detect that which key is pressed?

### ISSUE THREAD

**Issue by akash07k** [HavenDV/H.Hooks#3]
What's the code to detect that which key/key combination is pressed?

**Comment by HavenDV** [comment]
Please check args.Keys or args.Keys.Values

**Comment by akash07k** [comment]
But I'm doing it like this and getting error:

Please help that how to exactly detect the key

**Comment by akash07k** [comment]
Getting error:
`if(args.Keys == Key.Escape)`
```
      Severity	Code	Description	Project	File	Line	Suppression State
      Error	CS0019	Operator '==' cannot be applied to operands of type 'Keys' and 'Key'	Strawberry	C:\Users\v-akkak\source\repos\Strawberry\Strawberry\MainWindow.xaml.cs	62	Active

```

**Comment by akash07k** [comment]
Oh, I understood it now! thanks bro.
But can't you do something so that we don't need to Create new instance of Keys class everytime?
Even the code like this also not intuitive:

```
Keys key = new Keys();
if(args.Keys == keys(Key.Escape))
```

**Comment by akash07k** [comment]
fUpdate:
The code below is not working:
```
                            if (args.Keys == new Keys(Key.Escape))
                                Console.Beep();

```
Please help

**Comment by akash07k** [comment]
And this code is working which is very bad way of accomplishing this which I don't want:
```
                            if (args.ToString() == Key.Escape.ToString())
                                Console.Beep();

```
@HavenDV Any help please?

**Comment by HavenDV** [comment]
Sorry, I'm sleeping at this time. The fact that the option with == operator does not work is obviously a bug

**Comment by HavenDV** [comment]
New way:
```cs
if (args.Keys.Are(Key.Control, Key.Escape)) {
    // Action
}
```

**Comment by akash07k** [comment]
@HavenDV 
Thanks a lot bro for fixing the == operator bug and thanks a tons for introducing new and simpler method as well as new release on nuget too.
You are really amazing!
