### ISSUE TITLE
How to get the current key from "e.Keys" when press or release?

### ISSUE THREAD

**Issue by dxh-sc** [HavenDV/H.Hooks#5]
example:
1. Down event:  for "Ctrl+Alt+P",  i will press 3 times, but i don't know which key i press, just see 3 keys(Ctrl,Alt and P).
2. Up event:  for "Ctrl+Alt+P",  when i release "Alt", i don't know which key i release, just see 3 keys(Ctrl,Alt and P), but i only release "Alt".

so do we have a way get that? or add a property for it?

Thanks!

**Comment by HavenDV** [comment]
I have added the `KeyboardEventArgs.CurrentKey` property in the latest update

**Comment by akash07k** [comment]
@HavenDV 
Bro, thanks a lot for introducing it.
You are really an amazing developer.
you act upon user requests very quickly

**Comment by dxh-sc** [comment]
@HavenDV 
Great, thanks a lot!!!

Very thanks!
